use_existing_cluster: true
modify_fstab: false
overrides:
  ceph:
    conf:
      osd:
        osd op queue: debug_random
        osd op queue cut off: debug_random
        osd debug verify cached snaps: true
